import Head from "next/head";
import Info from "@/components/Info";
import Search from "@/components/Search";
// import { api } from "@/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from Sonix Tone" });

  return (
    <>
      <Head>
        <title>Sonix Tone</title>
        <meta name="description" content="Generated by Fremen" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container flex min-h-screen max-w-7xl flex-col">
        <Search />
        <Info />
      </main>
    </>
  );
}
