export const guitars = [
  {
    id: 1,
    name: "Fender",
    country: "United States",
    established: 1946,
    website: "https://www.fender.com/",
    headquarters: "Scottsdale, Arizona, USA",
    founder: "Leo Fender",
    parentCompany: null,
    popularModels: [
      { id: 1, name: "Stratocaster", style: "ST Style" },
      { id: 2, name: "Telecaster", style: "T Style" },
      { id: 3, name: "Jazzmaster", style: "Alternative Design" },
      { id: 4, name: "Jaguar", style: "Alternative Design" },
      { id: 5, name: "Mustang", style: "Alternative Design" },
      { id: 6, name: "Duo-Sonic", style: "Alternative Design" },
      { id: 7, name: "Starcaster", style: "Semiacoustic" },
      { id: 8, name: "Coronado", style: "Semiacoustic" },
      { id: 9, name: "Lead Series", style: "Alternative Design" },
      { id: 10, name: "Bullet", style: "ST Style" },
      { id: 11, name: "Cyclone", style: "Alternative Design" },
      { id: 12, name: "Musicmaster", style: "ST Style" },
      { id: 13, name: "Esquire", style: "T Style" },
      { id: 14, name: "Bronco", style: "Alternative Design" },
    ],
  },
  {
    id: 2,
    name: "Gibson",
    country: "United States",
    established: 1902,
    website: "https://www.gibson.com/",
    headquarters: "Nashville, Tennessee, USA",
    founder: "Orville Gibson",
    parentCompany: null,
    popularModels: [
      { id: 1, name: "Les Paul", style: "Single Cut" },
      { id: 2, name: "SG", style: "Double Cut" },
      { id: 3, name: "ES-335", style: "Semiacoustic" },
      { id: 4, name: "Flying V", style: "Alternative Design" },
      { id: 5, name: "Explorer", style: "Alternative Design" },
      { id: 6, name: "Firebird", style: "Alternative Design" },
      { id: 7, name: "Melody Maker", style: "Single Cut" },
      { id: 8, name: "ES-339", style: "Semiacoustic" },
    ],
  },
  // {
  //   id: 3,
  //   name: "Ibanez",
  //   country: "Japan",
  //   established: 1957,
  //   website: "https://www.ibanez.com/",
  //   headquarters: "Nagoya, Japan",
  //   founder: "Hoshino Gakki",
  //   parentCompany: null,
  //   popularModels: ["RG", "S", "AZ", "JEM", "Artcore"],
  // },
  // {
  //   id: 4,
  //   name: "PRS Guitars (Paul Reed Smith)",
  //   country: "United States",
  //   established: 1985,
  //   website: "https://www.prsguitars.com/",
  //   headquarters: "Stevensville, Maryland, USA",
  //   founder: "Paul Reed Smith",
  //   parentCompany: null,
  //   popularModels: ["Custom 24", "SE Custom 24", "McCarty 594", "SE Standard 24", "SE Custom 22"],
  // },
  // {
  //   id: 5,
  //   name: "ESP (Electric Sound Products)",
  //   country: "Japan",
  //   established: 1975,
  //   website: "https://www.espguitars.com/",
  //   headquarters: "Tokyo, Japan",
  //   founder: "Hisatake Shibuya",
  //   parentCompany: null,
  //   popularModels: ["LTD EC-1000", "LTD MH-1000", "LTD M-400", "LTD H-1007", "ESP Eclipse"],
  // },
  // {
  //   id: 6,
  //   name: "Gretsch",
  //   country: "United States",
  //   established: 1883,
  //   website: "https://www.gretschguitars.com/",
  //   headquarters: "Scottsdale, Arizona, USA",
  //   founder: "Friedrich Gretsch",
  //   parentCompany: null,
  //   popularModels: ["G6120", "White Falcon", "Jet", "Streamliner", "Electromatic"],
  // },
  // {
  //   id: 7,
  //   name: "Epiphone",
  //   country: "United States",
  //   established: 1873,
  //   website: "https://www.epiphone.com/",
  //   headquarters: "Nashville, Tennessee, USA",
  //   founder: "Anastasios Stathopoulos",
  //   parentCompany: "Gibson",
  //   popularModels: ["Les Paul Standard", "SG Standard", "ES-335", "Casino", "Explorer"],
  // },
  // {
  //   id: 8,
  //   name: "Jackson",
  //   country: "United States",
  //   established: 1980,
  //   website: "https://www.jacksonguitars.com/",
  //   headquarters: "Scottsdale, Arizona, USA",
  //   founder: "Grover Jackson",
  //   parentCompany: "Fender",
  //   popularModels: ["Soloist", "Dinky", "Rhoads", "King V", "Kelly"],
  // },
  // {
  //   id: 9,
  //   name: "Yamaha",
  //   country: "Japan",
  //   established: 1966,
  //   website: "https://usa.yamaha.com/",
  //   headquarters: "Shizuoka, Japan",
  //   founder: "Torakusu Yamaha",
  //   parentCompany: null,
  //   popularModels: ["Pacific Series", "Revstar", "RGX", "Pacifica", "SA"],
  // },
  // {
  //   id: 10,
  //   name: "Schecter",
  //   country: "United States",
  //   established: 1976,
  //   website: "https://www.schecterguitars.com/",
  //   headquarters: "Sun Valley, California, USA",
  //   founder: "David Schecter",
  //   parentCompany: null,
  //   popularModels: ["Hellraiser C-1", "Omen Extreme-6", "Synyster Gates Custom", "Reaper Series", "Blackjack SLS"],
  // },
  // {
  //   id: 11,
  //   name: "Music Man (Ernie Ball)",
  //   country: "United States",
  //   established: 1974,
  //   website: "https://www.music-man.com/",
  //   headquarters: "San Luis Obispo, California, USA",
  //   founder: "Leo Fender, Forrest White, Tom Walker",
  //   parentCompany: null,
  //   popularModels: ["StingRay", "Cutlass", "Axis", "Luke", "Valentine"],
  // },
  // {
  //   id: 12,
  //   name: "Rickenbacker",
  //   country: "United States",
  //   established: 1931,
  //   website: "https://www.rickenbacker.com/",
  //   headquarters: "Santa Ana, California, USA",
  //   founder: "Adolph Rickenbacker, George Beauchamp",
  //   parentCompany: null,
  //   popularModels: ["330", "360", "4003", "620", "325"],
  // },
  // {
  //   id: 13,
  //   name: "G&L (George Fullerton and Leo Fender)",
  //   country: "United States",
  //   established: 1979,
  //   website: "https://glguitars.com/",
  //   headquarters: "Fullerton, California, USA",
  //   founder: "George Fullerton, Leo Fender",
  //   parentCompany: null,
  //   popularModels: ["Legacy", "ASAT Classic", "Comanche", "Tribute Series", "Invader"],
  // },
  // {
  //   id: 14,
  //   name: "Squier (Fender subsidiary)",
  //   country: "United States",
  //   established: 1982,
  //   website: "https://www.squierguitars.com/",
  //   headquarters: "Scottsdale, Arizona, USA",
  //   founder: "V.C. Squier",
  //   parentCompany: "Fender",
  //   popularModels: ["Classic Vibe", "Affinity Series", "Contemporary Series", "Vintage Modified", "Bullet"],
  // },
  // {
  //   id: 15,
  //   name: "Harley Benton",
  //   country: "Germany",
  //   established: 1998,
  //   website: "https://www.thomann.de/gb/harley_benton.html",
  //   headquarters: "Treppendorf, Germany",
  //   founder: "Hans Thomann",
  //   parentCompany: "Thomann",
  //   popularModels: ["ST-20 Series", "Fusion-II", "SC-Custom", "HB-35Plus", "DC-Junior"],
  // },
  // {
  //   id: 16,
  //   name: "Cort",
  //   country: "South Korea",
  //   established: 1960,
  //   website: "https://www.cortguitars.com/",
  //   headquarters: "Seongnam, South Korea",
  //   founder: "Yung H. Park",
  //   parentCompany: null,
  //   popularModels: ["Cort X-Series", "Cort KX-Series", "Cort G-Series", "Cort CR-Series", "Cort M-Series"],
  // },
  // {
  //   id: 17,
  //   name: "Tokai",
  //   country: "Japan",
  //   established: 1947,
  //   website: "https://www.tokai-guitars.co.jp/",
  //   headquarters: "Hamamatsu, Japan",
  //   founder: "Tadayouki Adachi",
  //   parentCompany: null,
  //   popularModels: ["Tokai Love Rock", "Tokai Springy Sound", "Tokai BreezySound", "Tokai Talbo", "Tokai Legacy"],
  // },
  // {
  //   id: 18,
  //   name: "FujiGen",
  //   country: "Japan",
  //   established: 1960,
  //   website: "https://www.fgn-guitars.com/",
  //   headquarters: "Matsumoto, Japan",
  //   founder: "Yoshihiro Hoshino",
  //   parentCompany: null,
  //   popularModels: ["FGN J-Standard", "FGN Expert", "FGN Neo Classic", "FGN Masterfield", "FGN Odyssey"],
  // },
  // {
  //   id: 19,
  //   name: "Guild",
  //   country: "United States",
  //   established: 1952,
  //   website: "https://guildguitars.com/",
  //   headquarters: "Oxnard, California, USA",
  //   founder: "Alfred Dronge",
  //   parentCompany: "Cordoba Music Group",
  //   popularModels: ["Starfire", "D-55", "Surfliner", "T-Bird ST", "Jetstar"],
  // },
  // {
  //   id: 20,
  //   name: "Others",
  //   country: "Unknown",
  //   established: 0,
  //   website: "/",
  //   headquarters: "Unknown",
  //   founder: "Unknown",
  //   parentCompany: "Unknown",
  //   popularModels: [],
  // },
];

// ST Style, T Style, Single Cut, Double Cut, Alternative Design, Semiacoustic, Headless

export const neck = {
  shapes: [
    {
      id: 1,
      name: "C-shaped neck",
      description:
        "The C-shaped neck is a popular choice and is commonly found on many electric guitars. It is characterized by a smooth, rounded profile that provides a comfortable grip for most players. The curvature resembles the letter C, and it's known for its versatile playability.",
    },
    {
      id: 2,
      name: "D-shaped neck",
      description:
        "The D-shaped neck is similar to the C-shaped neck but has a flatter back, resembling the letter D. It provides a more substantial feel and support for the thumb, making it preferred by players who prefer a thicker neck profile.",
    },
    {
      id: 3,
      name: "V-shaped neck",
      description:
        "The V-shaped neck has a distinctive V profile, where the back of the neck feels like the letter V. It is often associated with vintage-style guitars and can offer a unique feel, providing a firm grip for players who like that characteristic.",
    },
    {
      id: 4,
      name: "Slim/Thin neck",
      description:
        "Slim or thin necks have a shallower depth from front to back. These necks are preferred by players who like a faster playing experience and require less hand movement.",
    },
    {
      id: 5,
      name: "Wide neck",
      description:
        "Wide necks provide more space between the strings. These necks can be suitable for fingerstyle playing and for players with larger hands.",
    },
    {
      id: 6,
      name: "Compound radius neck",
      description:
        "Compound radius necks have a curved fingerboard with a changing radius. It's flatter near the nut for easy chord playing and gradually becomes more rounded towards the higher frets for comfortable lead playing.",
    },
  ],
  woods: [
    {
      id: 1,
      name: "Maple",
      description:
        "Maple is one of the most popular woods used for guitar necks. It is known for its bright, clear tone and excellent sustain. Maple necks often have a smooth, dense grain, which contributes to their stability and durability.",
    },
    {
      id: 2,
      name: "Mahogany",
      description:
        "Mahogany is another common wood choice for guitar necks, especially in combination with mahogany bodies. It provides a warm, rich tone and offers a smooth, comfortable playing experience.",
    },
    {
      id: 3,
      name: "Rosewood",
      description:
        "Rosewood is commonly used for the fretboards of guitar necks, but it is also occasionally used for the entire neck. It has a smooth, oily texture and adds warmth to the tone.",
    },
    {
      id: 4,
      name: "Ebony",
      description:
        "Like rosewood, ebony is often used for the fretboard, but it can also be used for the neck itself. Ebony is a dense wood that offers a smooth playing surface and contributes to a bright, articulate tone.",
    },
    {
      id: 5,
      name: "Walnut",
      description:
        "Walnut is a less common but still viable choice for guitar necks. It has a balanced tone with warm and bright qualities, and it can add visual appeal with its attractive grain patterns.",
    },
    {
      id: 6,
      name: "Sapele",
      description:
        "Sapele is similar to mahogany in terms of its tonal qualities and appearance. It is a stable wood with a warm sound, making it a suitable choice for guitar necks.",
    },
    {
      id: 7,
      name: "Wenge",
      description:
        "Wenge is a dense and durable wood known for its dark appearance and prominent grain patterns. It provides a clear, articulate tone and excellent sustain.",
    },
  ],
  fingerboards: [
    {
      id: 1,
      name: "Rosewood",
      description:
        "Rosewood is one of the most popular fingerboard materials. It is dense and has natural oils, providing a smooth playing surface and a warm, mellow tone. Indian Rosewood and Brazilian Rosewood are commonly used varieties.",
    },
    {
      id: 2,
      name: "Maple",
      description:
        "Maple fingerboards have a bright, snappy tone and a smooth feel. They are often finished with a clear gloss to protect the wood and enhance its appearance.",
    },
    {
      id: 3,
      name: "Ebony",
      description:
        "Ebony is a dense and smooth wood, providing a bright, articulate tone. It is commonly used on high-end guitars and offers a luxurious look.",
    },
    {
      id: 4,
      name: "Pau Ferro",
      description:
        "Also known as Bolivian Rosewood, Pau Ferro has similar tonal qualities to Rosewood, with warm and balanced tones and a smooth feel.",
    },
    {
      id: 5,
      name: "Mahogany",
      description:
        "Mahogany fingerboards are relatively rare but can offer a warm tone with good sustain. They are sometimes used on guitars with Mahogany necks and bodies for tonal consistency.",
    },
    {
      id: 6,
      name: "Wenge",
      description:
        "Wenge is a dense and durable wood, providing a clear and articulate tone with good sustain. It has a distinctive appearance with dark color and prominent grain patterns.",
    },
  ],
};
